name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  billing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: go.mod
      - run: go test -race ./...
      - run: go vet ./...
      - run: docker build --target billing-build .
  admission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.12"
      - run: pip install -r requirements-test.txt
      - run: python -m pytest test_server.py
